### ISSUE TITLE
Problem when @types/readable-stream version is updated to latest version in the range declared in package.json

### ISSUE THREAD

**Issue by kai670** [legastero/stanza#368]
package.json sets `@types/readable-stream` version to `^2.3.1` and package-lock.json to `2.3.2`. But when you do `npm install stanza` from another project, package-lock.json is not taken into account so the latest version available is instead installed. In this case this menas `2.3.3` is installed. The problem is stanza is not working with that version.

### How to reproduce
npm update @types/readable-stream
npm run compile

### Expected result
Code compile without errors

### Actual result

```
node_modules/@types/readable-stream/index.d.ts:137:18 - error TS2749: 'StringDecoder' refers to a value, but is being used as a type here.

137         decoder: StringDecoder | null;
                     ~~~~~~~~~~~~~
```

**Comment by legastero** [comment]
Should be fixed now in 12.1.8.

Issue was both the @types/readable-stream and @types/node package needed updating together.

**Comment by kai670** [comment]
Still not working for me in the project where I'm using stanza if I only update to the next version. Probably related with this:

```
├─┬ stanza@12.1.8
│ ├── @types/async@3.0.1
│ ├── @types/node@12.7.1
│ ├── @types/punycode@2.1.0
│ ├─┬ @types/readable-stream@2.3.3
│ │ ├── @types/node@11.13.10 deduped
│ │ └── safe-buffer@5.1.2 deduped
│ ├─┬ @types/tape@4.2.33
│ │ └── @types/node@11.13.10 deduped
│ ├─┬ @types/ws@6.0.2
│ │ └── @types/node@11.13.10 deduped
```

I suppose the problem is the `@types/node` under `@types/readable-stream@2.3.3` right? But I can't understand why npm is using that version and not the one specified by stanza...

But now if I remove the package-lock and let npm regenerate it works so maybe this is now a npm problem...

**Comment by kaburkett** [comment]
Yes I can confirm that I changed nothing in my project- just removed the yarn.lock with node modules folder and reinstalled. It fixed the error. Thanks
